name: researchdata
recipe: drupal9
config:
  php: '7.4'
  via: nginx
  webroot: .
  database: postgres
services:
  appserver:
    build:
      - composer install
  node:
    type: node
    globals:
      gulp-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node